name: Build & Release PDFSplit

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install pypdf pyinstaller

    - name: Build binary
      run: |
        pyinstaller split_pdf.py --onefile --name pdfsplit

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: pdfsplit-${{ runner.os }}
        path: dist/pdfsplit*
