name: Build and Release PDFSplit

on:
  push:
    tags:
      - 'v*'  # e.g., v1.0.0

permissions:
  contents: write  # needed to upload release assets

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install pypdf pyinstaller

    - name: Build binary
      run: |
        pyinstaller split_pdf.py --onefile --name pdfsplit

    - name: Rename binary
      run: |
        mkdir output
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          mv dist/pdfsplit.exe output/pdfsplit-windows.exe
        elif [[ "${{ runner.os }}" == "macOS" ]]; then
          mv dist/pdfsplit output/pdfsplit-macos
        else
          mv dist/pdfsplit output/pdfsplit-linux
        fi
      shell: bash

    - name: Upload release binaries
      uses: softprops/action-gh-release@v1
      with:
        files: output/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
