name: Build and Release PDFSplit

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0

permissions:
  contents: write  # Required to upload release assets

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller split_pdf.py --onefile --name pdfsplit

      - name: Rename and prepare binary
        run: |
          mkdir output
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            mv dist/pdfsplit.exe output/pdfsplit-windows.exe
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            mv dist/pdfsplit output/pdfsplit-macos
          else
            mv dist/pdfsplit output/pdfsplit-linux
          fi
        shell: bash

      - name: Upload release binaries
        uses: softprops/action-gh-release@v1
        with:
          files: output/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
